org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=false
kotlin.code.style=official
android.nonTransitiveRClass=true
AUTODRIVE_SUPABASE_URL=https://madkfvggyolmdberzmtb.supabase.co
AUTODRIVE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hZGtmdmdneW9sbWRiZXJ6bXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTI3OTgsImV4cCI6MjA4ODM4ODc5OH0.PhwanCZLjJ7Tc8SrbkYSWY9bVQT-9R6kez3CdcWGPMc
